# Generated by Django 4.2 on 2026-04-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_user_auth_provider_user_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
    ]
